### ISSUE TITLE
Tests for MODELGEN fail if creation of filter NACs and PACs is switched on

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#9] opened 2017-06-16 14:38 UTC
To reproduce:

- switch on creation of filter NACs/PACs in NoDECsPatterns
- run tests in /testsuite1_familiestopersons
- remember to remove Ibex.jar from the buildpath and add core.language and core.runtime to the MANIFEST (please keep these changes local)
- about half of the tests should fail (Optional complains as a get is invoked for an empty optional).  Calling get on an Optional is actually a bad idea in general.

Something strange here is that for the MODELGEN case, or any cases where NO_DEC patterns are not even required at all, we still try to generate them instead of doing this only when they are actually needed.  See TGGCompiler at the end of preparePatterns where the NoDECsPatterns are created whether they are required or not.

**Comment by anthonyanjorin** [comment] 2017-06-19 09:52
@erhanleblebici Strange that this problem doesn't occur for ibex@viatra.  Perhaps you have an idea for what the problem could be.

**Comment by erhanleblebici** [comment] 2017-06-22 11:35
in fact, MODELGEN matches do not invoke any of these NODEC-Patterns (they just invoke SRC/TRG/Corr-Context patterns).
Generation of NODEC-Patterns in all cases is currently a design choice and makes the life easier when switching between different DEC-modes. But the problem here seems to be related to patterns that are not invoked at all (or should not be invoked at all).

**Comment by anthonyanjorin** [comment] 2017-07-01 21:08
@FStolte I've now investigated this a bit, and it turns out that the problem is related to refinements.  The problem is that the filter AC analysis is currently executed for all TGG rules, even though this is senseless when they have refinements.  The point here is that this analysis should only be executed on the flattened rules and its results should then be integrated into the top-most level of the pattern network with "refinements".

The more general question here is how we want to handle this case -- so the fact that the compiler is aware of the two versions of the TGG (flattened and not), and handles them a bit differently, even using results from the flattened version for the other. 

Let's discuss this soon.  It is necessary to:

1. Get all tests running when filter AC creation is enabled (currently the analysis crashes for empty TGG rules in the refinement network, even though it shouldn't be run here at all).
2. Start working on integrating filter ACs for CC (flattened => not flattened), and generally getting the tests here running as well.
3. Perhaps simplify and unify how you are currently handling constraint NACs, i.e., how you transfer them from flattened to not flattened TGGs (you have implemented this already, right?).

**Comment by FStolte** [comment] 2017-07-03 12:11
I just committed a fix for this issue, the concrete problem was caused by accessing nodes of an empty rule (which in this case came from the refinements, but could generally also be present in a flattened TGG).

**Closed by FStolte** 2017-07-03 12:11 UTC
Labels: bug

**Comment by Arikae** [comment] 2017-07-03 12:43
Does this solve all known problems with ACs in ibex-democles?

**Comment by anthonyanjorin** [comment] 2017-07-03 13:57
for the moment, I think yes :)
